### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by RasmusB** [adafruit/Adafruit_CircuitPython_Prompt_Toolkit#3]
Hello,

I'm trying to install this library on a Raspberry Pi Pico running CircuitPython 9.1.1, but following the instruction it fails:

```
C:\Users\Rasmus>circup install adafruit_prompt_toolkit
Found device at D:\, running CircuitPython 9.1.1.
Searching for dependencies for: ['adafruit_prompt_toolkit']
WARNING:
        adafruit_prompt_toolkit is not a known CircuitPython library.
Ready to install: []
```

I'm running `circup-2.0.4` and `Python 3.12.0`

**Comment by FoamyGuy** [comment]
@RasmusB This library does not have an initial release and it hasn't been added to the Library Bundle, so it's not available to install via circup. Until that happens the main way to install it is to clone the repo or download it from Github and then manually copy the library into the `lib/` dir on your device.

@tannewt do you know / recall if this is waiting on anything specific before it gets a release and added to the Bundle?

**Comment by tannewt** [comment]
@FoamyGuy I think it was laziness on my part. I added this for our circuit pyrate work that didn't end up as a product so it wasn't urgent. I think it'd be fine to polish up and release.

**Comment by FoamyGuy** [comment]
This was resolved by https://github.com/adafruit/Adafruit_CircuitPython_Bundle/pull/470 Prompt Toolkit has a release and is in the Bundle now.
